# Generated by Django 5.0.3 on 2024-03-20 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecode', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('post', models.CharField(max_length=20)),
                ('joining', models.CharField(max_length=10)),
                ('basicpay', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=30)),
                ('birthdate', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecode', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('months', models.IntegerField()),
                ('workingdays', models.IntegerField()),
                ('finalpay', models.FloatField()),
            ],
        ),
    ]
