# Generated by Django 5.0.3 on 2024-03-20 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeManageApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salary',
            old_name='workingdays',
            new_name='overtime',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='name',
        ),
    ]
